import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TransitionLink from "./components/TransitionLink";
import Render from './components/Render'
import FadeLayer from "./components/FadeLayer";
import Nav from "./components/Nav/Nav";
import SmoothScroll from "./components/SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          {children}
        </SmoothScroll>
        {/* <div style={{color:"white",position: "absolute",top:"1%",left:"50%",transform:"translate(-50%,-50%)",zIndex:10}}>
            <TransitionLink href="/oldal">oldal</TransitionLink>
            <TransitionLink href="/">fing</TransitionLink>
        </div> */}
        <Nav />
        {/* <FadeLayer /> */}
        {/* <Render /> */}
      </body>
    </html>
  );
}
