"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TransitionLink from "./components/TransitionLink3D";
import Render from './components/Render'
import FadeLayer from "./components/FadeLayer";
import Nav from "./components/Nav/Nav";
import SmoothScroll from "./components/SmoothScroll";
import { ViewTransitions } from "next-view-transitions";
import { usePathname } from "next/navigation";
import Loader from "./components/Loader/Loader";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <ViewTransitions>
    <html lang="en">
    <head>
        <link
          rel="preload"
          href="acumin-pro-wide-medium.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="acumin-pro-wide-bold.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="acumin-pro-wide.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        </head>

      <body>
        <Loader />
        <SmoothScroll>
          {children}
        </SmoothScroll>
        {/* <div style={{color:"white",position: "absolute",top:"1%",left:"50%",transform:"translate(-50%,-50%)",zIndex:10}}>
            <TransitionLink href="/oldal">oldal</TransitionLink>
            <TransitionLink href="/">fing</TransitionLink>
        </div> */}
        <Nav />
        {/* <FadeLayer /> */}
        {/* <Render /> */}
      </body>
    </html>
    </ViewTransitions>
  );
}
